server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    #开启不注册server服务本身
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
#    \u5173\u95ED\u81EA\u6211\u4FDD\u62A4
#    enable-self-preservation: false
#    \u6E05\u7406\u95F4\u9694
#    eviction-interval-timer-in-ms: 60000
spring:
  application:
    name: eureka-server
